/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActivitySection: typeof import('./components/activity/ActivitySection.vue')['default']
    AnnouncementSection: typeof import('./components/announcement/AnnouncementSection.vue')['default']
    AssistantChat: typeof import('./components/assistant/AssistantChat.vue')['default']
    AvatarCropperDialog: typeof import('./components/user/AvatarCropperDialog.vue')['default']
    CheckinFootprintMap: typeof import('./components/user/CheckinFootprintMap.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSegmented: typeof import('element-plus/es')['ElSegmented']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FeedItem: typeof import('./components/feed/FeedItem.vue')['default']
    FeedSection: typeof import('./components/feed/FeedSection.vue')['default']
    Footer: typeof import('./components/common/Footer.vue')['default']
    Header: typeof import('./components/common/Header.vue')['default']
    HeroBanner: typeof import('./components/common/HeroBanner.vue')['default']
    LazyMount: typeof import('./components/common/LazyMount.vue')['default']
    LeaderboardSection: typeof import('./components/leaderboard/LeaderboardSection.vue')['default']
    MapContainer: typeof import('./components/map/MapContainer.vue')['default']
    NotificationBell: typeof import('./components/common/NotificationBell.vue')['default']
    POIApplicationDialog: typeof import('./components/map/POIApplicationDialog.vue')['default']
    PoiCategoryBadge: typeof import('./components/common/PoiCategoryBadge.vue')['default']
    PoiDetailDialog: typeof import('./components/map/PoiDetailDialog.vue')['default']
    PoiSharePanel: typeof import('./components/map/PoiSharePanel.vue')['default']
    RecommendedRouteSection: typeof import('./components/route/RecommendedRouteSection.vue')['default']
    RecommendedShareSection: typeof import('./components/recommendation/RecommendedShareSection.vue')['default']
    RoutePolyline: typeof import('./components/map/RoutePolyline.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserRouteCard: typeof import('./components/route/UserRouteCard.vue')['default']
    UserRouteSection: typeof import('./components/route/UserRouteSection.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
